### ISSUE TITLE
Uncaught NoSuchElementException

### ISSUE THREAD

**Issue by kallewesterling** [JpPjJp/Eurovision-web-scraper#1]
Great idea! Love it!

I ran into an issue with an uncaught `NoSuchElementException` from selenium. I wonder if it's a good idea to catch errors, somehow in the script?

```
Traceback (most recent call last):
  File "eu.py", line 38, in <module>
    acceptCookies = distanceDriver.find_element_by_xpath("//p[@class='fc-button-label']")
  File "/Users/kallewesterling/opt/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/kallewesterling/opt/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/kallewesterling/opt/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/kallewesterling/opt/anaconda3/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //p[@class='fc-button-label']
```

**Comment by JpPjJp** [comment]
Thanks Kalle! That is a good idea. It looks like you are not being prompted to accept cookies for whatever reason so I have added a try-except to that area. I'm sure I should probably introduce more try-excepts, though! 

What's your favourite Eurovision act, by the way XD?

**Comment by kallewesterling** [comment]
Sounds good :)

My favorite? This one, of course!
![mata-hari](https://user-images.githubusercontent.com/7298727/119278245-01b43880-bbf2-11eb-98d9-426f3a3abc83.gif)
